### ISSUE TITLE
Error running the monitoring sample ... incompatible requirements

### ISSUE THREAD

**Issue by kolban-google** [GoogleCloudPlatform/ai-platform-samples#392]
Following the documentation, I am trying to run the following sample:

https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/official/model_monitoring/model_monitoring.ipynb

when I run this in either Vertex AI Notebooks or Cololab, it errors out at the cell "Setup your dependencies".

```
ERROR: google-colab 1.0.0 has requirement requests~=2.23.0, but you'll have requests 2.25.1 which is incompatible.
ERROR: google-cloud-bigquery 1.21.0 has requirement google-resumable-media!=0.4.0,<0.5.0dev,>=0.3.1, but you'll have google-resumable-media 1.3.1 which is incompatible.
ERROR: earthengine-api 0.1.269 has requirement google-api-python-client<2,>=1.12.1, but you'll have google-api-python-client 2.12.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
```

I am unable to follow the lab ... and since this is also linked to the Monitoring documentation at the GCP web pages, I think this is quite a serious issue.

**Comment by kweinmeister** [comment]
This notebook is being updated in the [GoogleCloudPlatform/vertex-ai-samples](https://github.com/GoogleCloudPlatform/vertex-ai-samples] repo. You can find the latest version [here](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/notebooks/official/model_monitoring/model_monitoring.ipynb).

Also, please note that in many cases, Python dependency constraint errors may not have any functional consequences in the notebook. It will be helpful to know if you see errors after executing the rest of the notebook cells.

I will go ahead and close the issue here. Please feel free to reopen the issue in the `vertex-ai-samples` repo if you are continuing to see issues with the latest version of the notebook.
