### ISSUE TITLE
VertexAI Featurestore batch serving writes null values to the bigquery table

### ISSUE THREAD

**Issue by abhishekkanojiya** [GoogleCloudPlatform/ai-platform-samples#416]
We are trying the example in the documentation for batch serving. The code seemed to work fine 3-4 days ago but since yesterday, we observed this behaviour that it is not writing feature values from the featurestore to the bigquery table, the csv file used for mapping writes it's data as expected, for eg. the entity types and the timestamp, but the respective features are written as null values instead.
one can find all the code and steps to run in this notebook
https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/official/feature_store/gapic-feature-store.ipynb

[](https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/official/feature_store/gapic-feature-store.ipynb)

**Comment by kweinmeister** [comment]
Thanks for letting us know!

Vertex AI content is now in the [GoogleCloudPlatform/vertex-ai-samples](https://github.com/GoogleCloudPlatform/vertex-ai-samples) repo. You can find the latest Feature Store notebook [here](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/notebooks/official/feature_store/gapic-feature-store.ipynb).

I will close the issue here, and please reopen an issue in that repo if you are still observing this issue with the latest notebook.
